<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container83pjtfn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container83pjtfn/appProdProjectContainer.php') {
    touch(__DIR__.'/Container83pjtfn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container83pjtfn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container83pjtfn\appProdProjectContainer([
    'container.build_hash' => '83pjtfn',
    'container.build_id' => '27bc9380',
    'container.build_time' => 1605719538,
], __DIR__.\DIRECTORY_SEPARATOR.'Container83pjtfn');
