<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIhxpqpo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIhxpqpo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIhxpqpo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIhxpqpo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIhxpqpo\appDevDebugProjectContainer([
    'container.build_hash' => 'Ihxpqpo',
    'container.build_id' => 'ba141da5',
    'container.build_time' => 1606478638,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIhxpqpo');
